modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="robotcraft"
version="1.0.0"
displayName="RobotCraft"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="batmanatorul, MCreator"

[[dependencies.robotcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



